services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    container_name: broker-service
    restart: always
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
